config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admins'
  devise_for :users, path: 'users'
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :draws, only: [:new, :create, :edit, :update, :destroy]
end

app/models/draw.rb
class Draw < ApplicationRecord
end

app/controllers/draws_controller.rb
class DrawsController < ApplicationController
    before_action :set_draw, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @draw = Draw.new
  end

  def create
    @draw = Draw.new(draw_params)
    # @draw.creator = current_user
    if @draw.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @draw.update(draw_params)
      redirect_to '/'
    else
      render :edit
    end
  end

  def destroy
    @draw.delete
    redirect_to root_path
  end

  private

  def set_draw
    @draw = Draw.find(params[:id])
  end

  def draw_params
    params.require(:draw).permit(:title, :description)
  end

end

app/views/draws/_index.html.erb
<h1>All my Draws</h1>
<ul>
  <% @draws.each do |draw| %>
  <li>
    <h3><%= draw.title %></h3>
    <p><%= draw.description %></p>
    <%= link_to edit_draw_path(draw) do %>
      <i class="fas fa-pen"></i>
      <p>Edit my draw</p>
    <% end %>
    <%= link_to 'Delete my draw',  draw_path(draw),
    data: { confirm: 'Are you sure?' }, method: :delete %>
  </li>
  <% end %>
</ul>

app/views/draws/_show.hmtl.erb
<h1>All my Draws</h1>
<ul>
  <% @draws.each do |draw| %>
    <%= draw.title %>
    <%= draw.description %>
  <% end %>
</ul>

app/views/draws/edit.html.erb
<h1>Create a new draw</h1>

<%= simple_form_for(@draw) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.submit %>
<% end %>

<%= link_to root_path do %>
 <p>Back to my list</p>
<% end %>

app/views/draws/new.html.erb
<h1>Create a new draw</h1>

<%= simple_form_for(@draw) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.submit %>
<% end %>

<%= link_to root_path do %>
  <p>Cancel</p>
<% end %>